name: excelOpt_env
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - dill
  - xlwings
  - jupyter
  - ipython
  - matplotlib
  - seaborn
  - plotly
  - dash
  - numba
